/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DesktopStickyNotesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/electron.ts
var import_obsidian = require("obsidian");
var STICKY_WINDOW_CLASS = "desktop-sticky-popout-window";
var HIDDEN_TITLEBAR_CLASS = "desktop-sticky-titlebar-hidden";
var CHROME_STYLE_ID = "desktop-sticky-window-chrome-style";
var chromeObservers = /* @__PURE__ */ new WeakMap();
var chromeHideSelectors = [
  ".titlebar",
  ".app-title-bar",
  ".workspace-tab-header-container",
  ".workspace-ribbon",
  ".status-bar",
  ".sidebar-toggle-button",
  ".workspace-sidedock-vault-profile",
  ".workspace-tab-container-before",
  ".workspace-tab-container-after"
];
function getRemoteFromWindow(win) {
  const candidate = win;
  if (typeof candidate.require === "function") {
    try {
      return candidate.require("@electron/remote");
    } catch (_error) {
    }
  }
  const globalCandidate = window;
  if (typeof globalCandidate.require === "function") {
    try {
      return globalCandidate.require("@electron/remote");
    } catch (_error) {
    }
  }
  return null;
}
function getDocumentForLeaf(leaf) {
  try {
    return leaf.getContainer().win.document;
  } catch (_error) {
    return null;
  }
}
function ensureChromeStyle(doc) {
  var _a;
  if (doc.getElementById(CHROME_STYLE_ID)) return;
  const styleEl = doc.createElement("style");
  styleEl.id = CHROME_STYLE_ID;
  styleEl.textContent = `
html.${STICKY_WINDOW_CLASS},
body.${STICKY_WINDOW_CLASS} {
  background: transparent !important;
  overflow: hidden !important;
}
body.${STICKY_WINDOW_CLASS} .workspace-leaf-content[data-type="desktop-sticky-note"] .view-header {
  display: none !important;
}
body.${HIDDEN_TITLEBAR_CLASS} .titlebar,
body.${HIDDEN_TITLEBAR_CLASS} .app-title-bar,
body.${HIDDEN_TITLEBAR_CLASS} .workspace-tab-header-container,
body.${HIDDEN_TITLEBAR_CLASS} .workspace-ribbon,
body.${HIDDEN_TITLEBAR_CLASS} .status-bar,
body.${HIDDEN_TITLEBAR_CLASS} .sidebar-toggle-button,
body.${HIDDEN_TITLEBAR_CLASS} .workspace-sidedock-vault-profile,
body.${HIDDEN_TITLEBAR_CLASS} .workspace-tab-container-before,
body.${HIDDEN_TITLEBAR_CLASS} .workspace-tab-container-after {
  display: none !important;
}
body.${STICKY_WINDOW_CLASS} .app-container,
body.${STICKY_WINDOW_CLASS} .horizontal-main-container,
body.${STICKY_WINDOW_CLASS} .workspace,
body.${STICKY_WINDOW_CLASS} .workspace-split,
body.${STICKY_WINDOW_CLASS} .workspace-tabs,
body.${STICKY_WINDOW_CLASS} .workspace-leaf,
body.${STICKY_WINDOW_CLASS} .workspace-leaf-content,
body.${STICKY_WINDOW_CLASS} .view-content {
  width: 100vw !important;
  height: 100vh !important;
  min-width: 0 !important;
  min-height: 0 !important;
  margin: 0 !important;
  padding: 0 !important;
  border: 0 !important;
  box-shadow: none !important;
  overflow: hidden !important;
  background: transparent !important;
}
body.${STICKY_WINDOW_CLASS} .workspace-split.mod-root,
body.${STICKY_WINDOW_CLASS} .workspace-tabs.mod-top,
body.${STICKY_WINDOW_CLASS} .workspace-tab-container,
body.${STICKY_WINDOW_CLASS} .workspace-tab-container-inner,
body.${STICKY_WINDOW_CLASS} .workspace-tab-container-inner > .workspace-leaf {
  width: 100vw !important;
  height: 100vh !important;
  margin: 0 !important;
  padding: 0 !important;
}
`;
  ((_a = doc.head) != null ? _a : doc.documentElement).appendChild(styleEl);
}
function applyInlineChromeVisibility(doc, hideWindowTitlebar) {
  for (const selector of chromeHideSelectors) {
    const elements = Array.from(doc.querySelectorAll(selector));
    for (const element of elements) {
      if (hideWindowTitlebar) {
        element.dataset.desktopStickyHidden = "true";
        element.style.setProperty("display", "none", "important");
      } else if (element.dataset.desktopStickyHidden === "true") {
        delete element.dataset.desktopStickyHidden;
        element.style.removeProperty("display");
      }
    }
  }
}
function enforceStickyChrome(doc, hideWindowTitlebar) {
  if (!doc.body || !doc.documentElement) return;
  ensureChromeStyle(doc);
  doc.body.classList.add(STICKY_WINDOW_CLASS);
  doc.documentElement.classList.add(STICKY_WINDOW_CLASS);
  doc.body.classList.toggle(HIDDEN_TITLEBAR_CLASS, hideWindowTitlebar);
  doc.documentElement.classList.toggle(HIDDEN_TITLEBAR_CLASS, hideWindowTitlebar);
  applyInlineChromeVisibility(doc, hideWindowTitlebar);
}
function installChromeObserver(doc, hideWindowTitlebar) {
  var _a;
  const existing = chromeObservers.get(doc);
  if (existing) {
    existing.hideWindowTitlebar = hideWindowTitlebar;
    return;
  }
  if (!doc.body) return;
  const win = (_a = doc.defaultView) != null ? _a : window;
  const state = {
    hideWindowTitlebar,
    applying: false,
    observer: new MutationObserver(() => {
      if (state.applying) return;
      state.applying = true;
      try {
        enforceStickyChrome(doc, state.hideWindowTitlebar);
      } finally {
        win.setTimeout(() => {
          state.applying = false;
        }, 0);
      }
    })
  };
  state.observer.observe(doc.documentElement, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ["class", "style"]
  });
  chromeObservers.set(doc, state);
}
function uninstallChromeObserver(doc) {
  const state = chromeObservers.get(doc);
  if (!state) return;
  state.observer.disconnect();
  chromeObservers.delete(doc);
}
function applyStickyWindowChrome(leaf, hideWindowTitlebar) {
  const doc = getDocumentForLeaf(leaf);
  if (!(doc == null ? void 0 : doc.body) || !doc.documentElement) return;
  enforceStickyChrome(doc, hideWindowTitlebar);
  installChromeObserver(doc, hideWindowTitlebar);
}
function releaseStickyWindowChrome(leaf) {
  var _a;
  const doc = getDocumentForLeaf(leaf);
  if (!(doc == null ? void 0 : doc.body) || !doc.documentElement) return;
  const win = (_a = doc.defaultView) != null ? _a : window;
  win.setTimeout(() => {
    var _a2;
    if (doc.querySelector('.workspace-leaf-content[data-type="desktop-sticky-note"]')) return;
    uninstallChromeObserver(doc);
    applyInlineChromeVisibility(doc, false);
    doc.body.classList.remove(STICKY_WINDOW_CLASS, HIDDEN_TITLEBAR_CLASS);
    doc.documentElement.classList.remove(STICKY_WINDOW_CLASS, HIDDEN_TITLEBAR_CLASS);
    (_a2 = doc.getElementById(CHROME_STYLE_ID)) == null ? void 0 : _a2.remove();
  }, 0);
}
function getBrowserWindowForWindow(win) {
  const remote = getRemoteFromWindow(win);
  if (!(remote == null ? void 0 : remote.getCurrentWindow)) return null;
  try {
    return remote.getCurrentWindow();
  } catch (_error) {
    return null;
  }
}
function getBrowserWindowForLeaf(leaf) {
  try {
    const container = leaf.getContainer();
    return getBrowserWindowForWindow(container.win);
  } catch (_error) {
    return null;
  }
}
function applyWindowBounds(leaf, sticky) {
  var _a, _b, _c;
  const browserWindow = getBrowserWindowForLeaf(leaf);
  if (!browserWindow || ((_a = browserWindow.isDestroyed) == null ? void 0 : _a.call(browserWindow))) return browserWindow;
  const bounds = {
    x: Math.round(sticky.x),
    y: Math.round(sticky.y),
    width: Math.max(240, Math.round(sticky.width)),
    height: Math.max(180, Math.round(sticky.height))
  };
  try {
    (_b = browserWindow.setBounds) == null ? void 0 : _b.call(browserWindow, bounds, false);
  } catch (_error) {
    try {
      (_c = browserWindow.setSize) == null ? void 0 : _c.call(browserWindow, bounds.width, bounds.height, false);
    } catch (__error) {
    }
  }
  return browserWindow;
}
function applyWindowPreferences(leaf, sticky, options) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m;
  applyStickyWindowChrome(leaf, options.hideWindowTitlebar);
  const browserWindow = getBrowserWindowForLeaf(leaf);
  if (!browserWindow) {
    if (options.showNotice) {
      new import_obsidian.Notice("\u65E0\u6CD5\u8BBF\u95EE Electron \u7A97\u53E3 API\uFF1A\u4FBF\u7B7E\u4ECD\u4F1A\u6253\u5F00\uFF0C\u4F46\u7F6E\u9876/\u900F\u660E\u5EA6/\u6807\u9898\u680F\u63A7\u5236\u53EF\u80FD\u4E0D\u53EF\u7528\u3002", 6e3);
    }
    return null;
  }
  try {
    (_a = browserWindow.setAlwaysOnTop) == null ? void 0 : _a.call(browserWindow, sticky.alwaysOnTop, "floating");
  } catch (_error) {
    if (options.showNotice) new import_obsidian.Notice("\u5F53\u524D\u7CFB\u7EDF\u4E0D\u652F\u6301\u8BBE\u7F6E\u4FBF\u7B7E\u7A97\u53E3\u7F6E\u9876\u3002", 5e3);
  }
  try {
    (_b = browserWindow.setOpacity) == null ? void 0 : _b.call(browserWindow, sticky.opacity);
  } catch (_error) {
  }
  try {
    (_c = browserWindow.setSkipTaskbar) == null ? void 0 : _c.call(browserWindow, options.skipTaskbar);
  } catch (_error) {
  }
  try {
    (_d = browserWindow.setBackgroundColor) == null ? void 0 : _d.call(browserWindow, "#00000000");
  } catch (_error) {
  }
  if (options.hideWindowTitlebar) {
    try {
      (_e = browserWindow.setAutoHideMenuBar) == null ? void 0 : _e.call(browserWindow, true);
      (_f = browserWindow.setMenuBarVisibility) == null ? void 0 : _f.call(browserWindow, false);
    } catch (_error) {
    }
    try {
      (_g = browserWindow.setTitle) == null ? void 0 : _g.call(browserWindow, " ");
    } catch (_error) {
    }
    try {
      (_h = browserWindow.setWindowButtonVisibility) == null ? void 0 : _h.call(browserWindow, false);
    } catch (_error) {
    }
    try {
      (_i = browserWindow.setTitleBarOverlay) == null ? void 0 : _i.call(browserWindow, { color: "#00000000", symbolColor: "#00000000", height: 0 });
    } catch (_error) {
    }
  } else {
    try {
      (_j = browserWindow.setAutoHideMenuBar) == null ? void 0 : _j.call(browserWindow, false);
      (_k = browserWindow.setMenuBarVisibility) == null ? void 0 : _k.call(browserWindow, true);
      (_l = browserWindow.setWindowButtonVisibility) == null ? void 0 : _l.call(browserWindow, true);
      (_m = browserWindow.setTitle) == null ? void 0 : _m.call(browserWindow, "Desktop Sticky Notes");
    } catch (_error) {
    }
  }
  return browserWindow;
}
function captureWindowBounds(browserWindow) {
  var _a;
  try {
    const bounds = (_a = browserWindow.getBounds) == null ? void 0 : _a.call(browserWindow);
    if (!bounds) return null;
    return {
      x: bounds.x,
      y: bounds.y,
      width: bounds.width,
      height: bounds.height
    };
  } catch (_error) {
    return null;
  }
}

// src/note-suggest-modal.ts
var import_obsidian2 = require("obsidian");
var NoteSuggestModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, onChooseFile) {
    super(app);
    this.onChooseFile = onChooseFile;
    this.setPlaceholder("\u9009\u62E9\u8981\u8D34\u5230\u684C\u9762\u7684 Markdown \u7B14\u8BB0\u2026");
    this.emptyStateText = "\u6CA1\u6709\u627E\u5230\u5339\u914D\u7684 Markdown \u7B14\u8BB0";
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChooseFile(file);
  }
};

// src/settings-tab.ts
var import_obsidian3 = require("obsidian");

// src/types.ts
var VIEW_TYPE_STICKY_NOTE = "desktop-sticky-note";
var DEFAULT_SETTINGS = {
  stickies: {},
  restoreOnStartup: true,
  defaultAlwaysOnTop: true,
  skipTaskbar: false,
  hideWindowTitlebar: true,
  defaultWidth: 360,
  defaultHeight: 360,
  defaultOpacity: 1,
  defaultColor: "yellow",
  defaultMode: "preview",
  autoSaveDelayMs: 700,
  newNoteFolder: "Sticky Notes",
  newNoteTemplate: "",
  focusNewSticky: true,
  reuseExistingStickyForSameFile: true
};
var STICKY_COLORS = ["yellow", "blue", "green", "pink", "purple", "gray"];

// src/settings-tab.ts
function parsePositiveInteger(value, fallback, min, max) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(max, Math.max(min, parsed));
}
function parseOpacity(value, fallback) {
  const parsed = Number.parseFloat(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(1, Math.max(0.2, parsed));
}
var DesktopStickyNotesSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Desktop Sticky Notes" });
    containerEl.createEl("p", {
      text: "\u628A Obsidian \u7B14\u8BB0\u6253\u5F00\u4E3A\u684C\u9762\u4FBF\u7B7E\u7A97\u53E3\u3002\u7F6E\u9876\u3001\u900F\u660E\u5EA6\u548C\u4EFB\u52A1\u680F\u884C\u4E3A\u4F9D\u8D56 Electron \u684C\u9762\u7AEF\u80FD\u529B\u3002",
      cls: "desktop-sticky-settings-desc"
    });
    new import_obsidian3.Setting(containerEl).setName("\u542F\u52A8\u65F6\u6062\u590D\u4FBF\u7B7E").setDesc("\u91CD\u65B0\u6253\u5F00 Obsidian \u540E\u81EA\u52A8\u6062\u590D\u4E0A\u6B21\u56FA\u5B9A\u7684\u4FBF\u7B7E\u7A97\u53E3\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.restoreOnStartup).onChange(async (value) => {
      this.plugin.settings.restoreOnStartup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u65B0\u4FBF\u7B7E\u9ED8\u8BA4\u7F6E\u9876").setDesc("\u8BA9\u65B0\u6253\u5F00\u7684\u4FBF\u7B7E\u7A97\u53E3\u4FDD\u6301\u5728\u5176\u4ED6\u5E94\u7528\u7A97\u53E3\u524D\u65B9\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.defaultAlwaysOnTop).onChange(async (value) => {
      this.plugin.settings.defaultAlwaysOnTop = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u4FBF\u7B7E\u4E0D\u663E\u793A\u5728\u4EFB\u52A1\u680F").setDesc("\u9002\u5408\u628A\u4FBF\u7B7E\u5F53\u4F5C\u684C\u9762\u5C0F\u7EC4\u4EF6\u4F7F\u7528\uFF1B\u4E0D\u540C\u7CFB\u7EDF\u8868\u73B0\u53EF\u80FD\u4E0D\u540C\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.skipTaskbar).onChange(async (value) => {
      this.plugin.settings.skipTaskbar = value;
      await this.plugin.saveSettings();
      await this.plugin.applyPreferencesToOpenStickies();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u9690\u85CF\u4FBF\u7B7E\u7A97\u53E3\u6807\u9898\u680F").setDesc("\u6253\u5F00\u4FBF\u7B7E\u65F6\u9690\u85CF Obsidian \u5F39\u51FA\u7A97\u53E3\u7684\u6807\u9898\u680F\uFF0C\u5E76\u4F7F\u7528\u4FBF\u7B7E\u9876\u90E8\u5DE5\u5177\u6761\u4F5C\u4E3A\u62D6\u52A8\u533A\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideWindowTitlebar).onChange(async (value) => {
      this.plugin.settings.hideWindowTitlebar = value;
      await this.plugin.saveSettings();
      await this.plugin.applyPreferencesToOpenStickies();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u540C\u4E00\u7B14\u8BB0\u590D\u7528\u73B0\u6709\u4FBF\u7B7E").setDesc("\u5F00\u542F\u540E\uFF0C\u5982\u679C\u67D0\u7BC7\u7B14\u8BB0\u5DF2\u7ECF\u88AB\u8D34\u51FA\uFF0C\u518D\u6B21\u6267\u884C\u547D\u4EE4\u4F1A\u6253\u5F00/\u805A\u7126\u73B0\u6709\u4FBF\u7B7E\uFF0C\u800C\u4E0D\u662F\u521B\u5EFA\u7B2C\u4E8C\u4E2A\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.reuseExistingStickyForSameFile).onChange(async (value) => {
      this.plugin.settings.reuseExistingStickyForSameFile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u5BBD\u5EA6").setDesc("\u65B0\u4FBF\u7B7E\u7A97\u53E3\u9ED8\u8BA4\u5BBD\u5EA6\uFF0C\u5355\u4F4D\u50CF\u7D20\u3002").addText((text) => text.setPlaceholder("360").setValue(String(this.plugin.settings.defaultWidth)).onChange(async (value) => {
      this.plugin.settings.defaultWidth = parsePositiveInteger(value, this.plugin.settings.defaultWidth, 240, 1200);
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u9AD8\u5EA6").setDesc("\u65B0\u4FBF\u7B7E\u7A97\u53E3\u9ED8\u8BA4\u9AD8\u5EA6\uFF0C\u5355\u4F4D\u50CF\u7D20\u3002").addText((text) => text.setPlaceholder("360").setValue(String(this.plugin.settings.defaultHeight)).onChange(async (value) => {
      this.plugin.settings.defaultHeight = parsePositiveInteger(value, this.plugin.settings.defaultHeight, 180, 1200);
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5C06\u5F53\u524D\u9ED8\u8BA4\u5C3A\u5BF8\u5E94\u7528\u5230\u5DF2\u56FA\u5B9A\u4FBF\u7B7E").setDesc("\u5DF2\u6709\u4FBF\u7B7E\u4F1A\u8BB0\u4F4F\u81EA\u5DF1\u7684\u5C3A\u5BF8\uFF1B\u5982\u679C\u65E7\u4FBF\u7B7E\u5C3A\u5BF8\u4E0D\u5BF9\uFF0C\u53EF\u7528\u8FD9\u4E2A\u6309\u94AE\u7EDF\u4E00\u91CD\u7F6E\u4E3A\u4E0A\u65B9\u9ED8\u8BA4\u5BBD\u9AD8\u3002").addButton((button) => button.setButtonText("\u5E94\u7528\u9ED8\u8BA4\u5C3A\u5BF8").onClick(async () => {
      await this.plugin.applyDefaultSizeToAllStickies();
      this.display();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u900F\u660E\u5EA6").setDesc("\u8303\u56F4 0.2 \u5230 1\u30021 \u8868\u793A\u4E0D\u900F\u660E\u3002").addText((text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.defaultOpacity)).onChange(async (value) => {
      this.plugin.settings.defaultOpacity = parseOpacity(value, this.plugin.settings.defaultOpacity);
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u989C\u8272").setDesc("\u65B0\u4FBF\u7B7E\u7684\u9ED8\u8BA4\u80CC\u666F\u8272\u3002").addDropdown((dropdown) => {
      for (const color of STICKY_COLORS) dropdown.addOption(color, color);
      dropdown.setValue(this.plugin.settings.defaultColor).onChange(async (value) => {
        this.plugin.settings.defaultColor = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u6A21\u5F0F").setDesc("\u65B0\u4FBF\u7B7E\u6253\u5F00\u65F6\u4F7F\u7528\u9884\u89C8\u6A21\u5F0F\u8FD8\u662F\u7F16\u8F91\u6A21\u5F0F\u3002").addDropdown((dropdown) => dropdown.addOption("preview", "\u9884\u89C8").addOption("edit", "\u7F16\u8F91").setValue(this.plugin.settings.defaultMode).onChange(async (value) => {
      this.plugin.settings.defaultMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u81EA\u52A8\u4FDD\u5B58\u5EF6\u8FDF").setDesc("\u7F16\u8F91\u6A21\u5F0F\u4E0B\u505C\u6B62\u8F93\u5165\u591A\u4E45\u540E\u4FDD\u5B58\uFF0C\u5355\u4F4D\u6BEB\u79D2\u3002").addText((text) => text.setPlaceholder("700").setValue(String(this.plugin.settings.autoSaveDelayMs)).onChange(async (value) => {
      this.plugin.settings.autoSaveDelayMs = parsePositiveInteger(value, this.plugin.settings.autoSaveDelayMs, 200, 1e4);
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u65B0\u5EFA\u4FBF\u7B7E\u76EE\u5F55").setDesc("\u6267\u884C\u201C\u65B0\u5EFA\u684C\u9762\u4FBF\u7B7E\u201D\u547D\u4EE4\u65F6\uFF0C\u65B0 Markdown \u6587\u4EF6\u5C06\u521B\u5EFA\u5728\u6B64\u76EE\u5F55\u3002").addText((text) => text.setPlaceholder("Sticky Notes").setValue(this.plugin.settings.newNoteFolder).onChange(async (value) => {
      this.plugin.settings.newNoteFolder = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u65B0\u5EFA\u4FBF\u7B7E\u6A21\u677F").setDesc("\u65B0\u5EFA\u4FBF\u7B7E\u65F6\u5199\u5165\u6587\u4EF6\u7684\u521D\u59CB\u5185\u5BB9\u3002\u652F\u6301 {{date}} \u548C {{time}}\u3002").addTextArea((text) => {
      text.inputEl.rows = 5;
      text.setPlaceholder("\u4F8B\u5982\uFF1A# {{date}}\n\n- ").setValue(this.plugin.settings.newNoteTemplate).onChange(async (value) => {
        this.plugin.settings.newNoteTemplate = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "\u5DF2\u56FA\u5B9A\u4FBF\u7B7E" });
    const stickyStates = Object.values(this.plugin.settings.stickies).sort((a, b) => {
      var _a, _b;
      return ((_a = b.lastOpenedAt) != null ? _a : b.updatedAt) - ((_b = a.lastOpenedAt) != null ? _b : a.updatedAt);
    });
    if (stickyStates.length === 0) {
      containerEl.createEl("p", { text: "\u8FD8\u6CA1\u6709\u56FA\u5B9A\u4EFB\u4F55\u4FBF\u7B7E\u3002", cls: "desktop-sticky-empty" });
      return;
    }
    for (const sticky of stickyStates) {
      new import_obsidian3.Setting(containerEl).setName(sticky.filePath).setDesc(`${sticky.width}x${sticky.height} \xB7 ${sticky.color} \xB7 ${sticky.alwaysOnTop ? "\u7F6E\u9876" : "\u4E0D\u7F6E\u9876"}`).addButton((button) => button.setButtonText("\u6253\u5F00").onClick(async () => this.plugin.openSticky(sticky.id))).addButton((button) => button.setButtonText("\u79FB\u9664").setWarning().onClick(async () => {
        await this.plugin.removeSticky(sticky.id, true);
        this.display();
      }));
    }
  }
};

// src/sticky-view.ts
var import_obsidian4 = require("obsidian");
function isStickyViewState(state) {
  return typeof state === "object" && state !== null && typeof state.stickyId === "string";
}
function fileNameWithoutExtension(file) {
  return file.basename || file.name.replace(/\.md$/i, "");
}
var StickyNoteView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.stickyId = null;
    this.file = null;
    this.content = "";
    this.lastSavedContent = "";
    this.saveTimer = null;
    this.headerHideTimer = null;
    this.isSaving = false;
    this.rootEl = null;
    this.bodyEl = null;
    this.statusEl = null;
    this.plugin = plugin;
    this.navigation = false;
    this.icon = "sticky-note";
  }
  getViewType() {
    return VIEW_TYPE_STICKY_NOTE;
  }
  getDisplayText() {
    const sticky = this.currentSticky();
    if (!sticky) return "Desktop sticky note";
    const file = this.plugin.getFile(sticky.filePath);
    return file ? fileNameWithoutExtension(file) : sticky.filePath;
  }
  getState() {
    return {
      ...super.getState(),
      stickyId: this.stickyId
    };
  }
  async setState(state, result) {
    await super.setState(state, result);
    if (isStickyViewState(state)) {
      this.stickyId = state.stickyId;
      await this.loadAndRender();
    }
  }
  async onOpen() {
    this.contentEl.addClass("desktop-sticky-note-host");
    applyStickyWindowChrome(this.leaf, this.plugin.settings.hideWindowTitlebar);
    this.registerEvent(this.app.vault.on("modify", async (file) => {
      if (!(file instanceof import_obsidian4.TFile)) return;
      if (!this.file || file.path !== this.file.path) return;
      if (this.isSaving) return;
      await this.reloadFileFromDisk({ preserveEditText: false });
    }));
    this.registerEvent(this.app.vault.on("rename", async (file, oldPath) => {
      if (!(file instanceof import_obsidian4.TFile)) return;
      const sticky = this.currentSticky();
      if (!sticky || sticky.filePath !== oldPath) return;
      await this.plugin.updateSticky(sticky.id, { filePath: file.path });
      await this.loadAndRender();
    }));
  }
  async onClose() {
    this.clearHeaderHideTimer();
    await this.flushSave();
    if (this.stickyId) this.plugin.markStickyClosed(this.stickyId, this.leaf);
    releaseStickyWindowChrome(this.leaf);
  }
  onPaneMenu(menu) {
    const sticky = this.currentSticky();
    if (!sticky) return;
    menu.addItem((item) => item.setTitle(sticky.mode === "edit" ? "\u5207\u6362\u5230\u9884\u89C8" : "\u5207\u6362\u5230\u7F16\u8F91").setIcon(sticky.mode === "edit" ? "eye" : "pencil").onClick(async () => this.toggleMode()));
    menu.addItem((item) => item.setTitle(sticky.alwaysOnTop ? "\u53D6\u6D88\u7F6E\u9876" : "\u7A97\u53E3\u7F6E\u9876").setIcon("pin").onClick(async () => this.toggleAlwaysOnTop()));
    menu.addItem((item) => item.setTitle("\u5207\u6362\u4FBF\u7B7E\u989C\u8272").setIcon("palette").onClick(async () => this.cycleColor()));
    menu.addItem((item) => item.setTitle("\u5728 Obsidian \u4E2D\u6253\u5F00\u539F\u7B14\u8BB0").setIcon("file-text").onClick(async () => this.openSourceNote()));
    menu.addSeparator();
    menu.addItem((item) => item.setTitle("\u53D6\u6D88\u56FA\u5B9A\u8FD9\u4E2A\u4FBF\u7B7E").setIcon("trash").setWarning(true).onClick(async () => {
      if (this.stickyId) await this.plugin.removeSticky(this.stickyId, true);
    }));
  }
  currentSticky() {
    var _a;
    if (!this.stickyId) return null;
    return (_a = this.plugin.settings.stickies[this.stickyId]) != null ? _a : null;
  }
  async loadAndRender() {
    const sticky = this.currentSticky();
    if (!sticky) {
      this.renderMissing("\u4FBF\u7B7E\u72B6\u6001\u4E0D\u5B58\u5728\u3002\u5B83\u53EF\u80FD\u5DF2\u7ECF\u88AB\u79FB\u9664\u3002 ");
      return;
    }
    const file = this.plugin.getFile(sticky.filePath);
    if (!file) {
      this.renderMissing(`\u627E\u4E0D\u5230\u7B14\u8BB0\uFF1A${sticky.filePath}`);
      return;
    }
    this.file = file;
    this.content = await this.app.vault.read(file);
    this.lastSavedContent = this.content;
    this.renderSticky(sticky, file);
    applyWindowPreferences(this.leaf, sticky, {
      skipTaskbar: this.plugin.settings.skipTaskbar,
      hideWindowTitlebar: this.plugin.settings.hideWindowTitlebar,
      showNotice: false
    });
  }
  renderMissing(message) {
    this.contentEl.empty();
    const wrapper = this.contentEl.createDiv({ cls: "desktop-sticky-note desktop-sticky-note-missing" });
    wrapper.createEl("strong", { text: "Desktop Sticky Notes" });
    wrapper.createEl("p", { text: message });
    const closeButton = wrapper.createEl("button", { text: "\u5173\u95ED" });
    closeButton.addEventListener("click", () => this.leaf.detach());
  }
  renderSticky(sticky, file) {
    this.clearHeaderHideTimer();
    this.statusEl = null;
    this.contentEl.empty();
    this.rootEl = this.contentEl.createDiv({
      cls: `desktop-sticky-note desktop-sticky-note-${sticky.color} desktop-sticky-note-${sticky.mode}${sticky.alwaysOnTop ? " is-pinned" : ""}`
    });
    const header = this.rootEl.createDiv({ cls: "desktop-sticky-header" });
    const title = header.createDiv({ cls: "desktop-sticky-title" });
    const titleText = title.createSpan({ text: fileNameWithoutExtension(file), cls: "desktop-sticky-title-text" });
    titleText.setAttribute("title", file.path);
    const actions = header.createDiv({ cls: "desktop-sticky-actions" });
    this.addIconButton(actions, sticky.alwaysOnTop ? "pin-off" : "pin", sticky.alwaysOnTop ? "\u53D6\u6D88\u7F6E\u9876" : "\u7A97\u53E3\u7F6E\u9876", () => this.toggleAlwaysOnTop(), "is-pin");
    this.addIconButton(actions, sticky.mode === "edit" ? "eye" : "pencil", sticky.mode === "edit" ? "\u5207\u6362\u5230\u9884\u89C8" : "\u5207\u6362\u5230\u7F16\u8F91", () => this.toggleMode(), "is-mode");
    this.addIconButton(actions, "palette", "\u5207\u6362\u4FBF\u7B7E\u989C\u8272", () => this.cycleColor(), "is-color");
    this.addIconButton(actions, "external-link", "\u5728 Obsidian \u4E2D\u6253\u5F00\u539F\u7B14\u8BB0", () => this.openSourceNote(), "is-source");
    this.addIconButton(actions, "trash", "\u53D6\u6D88\u56FA\u5B9A\u8FD9\u4E2A\u4FBF\u7B7E", async () => {
      if (this.stickyId) await this.plugin.removeSticky(this.stickyId, true);
    }, "is-remove");
    this.addIconButton(actions, "x", "\u5173\u95ED\u4FBF\u7B7E", async () => {
      await this.flushSave();
      this.leaf.detach();
    }, "is-close");
    this.bodyEl = this.rootEl.createDiv({ cls: "desktop-sticky-body" });
    this.installHeaderAutoHide(this.rootEl);
    if (sticky.mode === "edit") {
      this.renderEditor();
    } else {
      void this.renderPreview();
    }
  }
  installHeaderAutoHide(root) {
    const showHeader = () => {
      this.clearHeaderHideTimer();
      root.classList.remove("is-header-hidden");
    };
    const scheduleHide = () => {
      this.clearHeaderHideTimer();
      this.headerHideTimer = window.setTimeout(() => {
        this.headerHideTimer = null;
        if (!root.isConnected) return;
        if (root.matches(":hover")) return;
        root.classList.add("is-header-hidden");
      }, 3e3);
    };
    root.addEventListener("mouseenter", showHeader);
    root.addEventListener("mousemove", showHeader);
    root.addEventListener("focusin", showHeader);
    root.addEventListener("mouseleave", scheduleHide);
    root.addEventListener("focusout", () => {
      window.setTimeout(() => {
        if (!root.contains(root.ownerDocument.activeElement)) scheduleHide();
      }, 0);
    });
  }
  clearHeaderHideTimer() {
    if (this.headerHideTimer === null) return;
    window.clearTimeout(this.headerHideTimer);
    this.headerHideTimer = null;
  }
  addIconButton(container, icon, tooltip, callback, extraClass) {
    const button = container.createEl("button", { cls: "desktop-sticky-icon-button", attr: { "aria-label": tooltip, type: "button" } });
    if (extraClass) button.addClass(extraClass);
    (0, import_obsidian4.setIcon)(button, icon);
    (0, import_obsidian4.setTooltip)(button, tooltip);
    button.addEventListener("click", (event) => {
      event.preventDefault();
      event.stopPropagation();
      void callback(event);
    });
    return button;
  }
  renderEditor() {
    if (!this.bodyEl) return;
    this.bodyEl.empty();
    const textarea = this.bodyEl.createEl("textarea", {
      cls: "desktop-sticky-editor",
      attr: { spellcheck: "true" }
    });
    textarea.value = this.content;
    textarea.addEventListener("input", () => {
      this.content = textarea.value;
      this.setStatus("\u6B63\u5728\u8F93\u5165\u2026");
      this.scheduleSave();
    });
    textarea.addEventListener("blur", () => void this.flushSave());
    window.setTimeout(() => textarea.focus(), 30);
  }
  async renderPreview() {
    if (!this.bodyEl || !this.file) return;
    this.bodyEl.empty();
    const previewEl = this.bodyEl.createDiv({ cls: "desktop-sticky-preview markdown-preview-view markdown-rendered" });
    await import_obsidian4.MarkdownRenderer.render(this.app, this.content, previewEl, this.file.path, this);
    this.setStatus(this.content.trim() ? "\u9884\u89C8" : "\u7A7A\u767D\u4FBF\u7B7E");
  }
  async toggleMode() {
    await this.flushSave();
    const sticky = this.currentSticky();
    if (!sticky) return;
    const nextMode = sticky.mode === "edit" ? "preview" : "edit";
    await this.plugin.updateSticky(sticky.id, { mode: nextMode });
    const latest = this.currentSticky();
    if (latest && this.file) this.renderSticky(latest, this.file);
  }
  async toggleAlwaysOnTop() {
    const sticky = this.currentSticky();
    if (!sticky) return;
    await this.plugin.updateSticky(sticky.id, { alwaysOnTop: !sticky.alwaysOnTop });
    const latest = this.currentSticky();
    if (!latest) return;
    applyWindowPreferences(this.leaf, latest, {
      skipTaskbar: this.plugin.settings.skipTaskbar,
      hideWindowTitlebar: this.plugin.settings.hideWindowTitlebar,
      showNotice: true
    });
    if (this.file) this.renderSticky(latest, this.file);
  }
  async cycleColor() {
    const sticky = this.currentSticky();
    if (!sticky || !this.file) return;
    const index = STICKY_COLORS.indexOf(sticky.color);
    const nextColor = STICKY_COLORS[(index + 1) % STICKY_COLORS.length];
    await this.plugin.updateSticky(sticky.id, { color: nextColor });
    const latest = this.currentSticky();
    if (latest) this.renderSticky(latest, this.file);
  }
  async openSourceNote() {
    if (!this.file) return;
    await this.app.workspace.getLeaf("tab").openFile(this.file);
    new import_obsidian4.Notice(`\u5DF2\u5728 Obsidian \u4E2D\u6253\u5F00\uFF1A${this.file.path}`, 2500);
  }
  scheduleSave() {
    if (this.saveTimer !== null) window.clearTimeout(this.saveTimer);
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      void this.flushSave();
    }, this.plugin.settings.autoSaveDelayMs);
  }
  async flushSave() {
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    if (!this.file) return;
    if (this.content === this.lastSavedContent) return;
    const contentToSave = this.content;
    this.isSaving = true;
    this.setStatus("\u4FDD\u5B58\u4E2D\u2026");
    try {
      await this.app.vault.process(this.file, () => contentToSave);
      this.lastSavedContent = contentToSave;
      this.setStatus("\u5DF2\u4FDD\u5B58");
      if (this.stickyId) await this.plugin.touchSticky(this.stickyId);
    } catch (error) {
      console.error("Desktop Sticky Notes: failed to save note", error);
      new import_obsidian4.Notice("\u4FBF\u7B7E\u4FDD\u5B58\u5931\u8D25\uFF0C\u8BF7\u67E5\u770B\u5F00\u53D1\u8005\u63A7\u5236\u53F0\u3002", 6e3);
      this.setStatus("\u4FDD\u5B58\u5931\u8D25");
    } finally {
      this.isSaving = false;
    }
  }
  async reloadFileFromDisk(options) {
    if (!this.file) return;
    const sticky = this.currentSticky();
    if (!sticky) return;
    const diskContent = await this.app.vault.read(this.file);
    this.lastSavedContent = diskContent;
    if (sticky.mode === "edit" && options.preserveEditText && this.content !== this.lastSavedContent) {
      return;
    }
    this.content = diskContent;
    if (this.file) this.renderSticky(sticky, this.file);
  }
  setStatus(message) {
    if (this.statusEl) this.statusEl.setText(message);
  }
};

// src/main.ts
function cloneDefaultSettings() {
  return {
    ...DEFAULT_SETTINGS,
    stickies: {}
  };
}
function makeId() {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
function debounce(fn, delayMs) {
  let timer = null;
  return ((...args) => {
    if (timer !== null) window.clearTimeout(timer);
    timer = window.setTimeout(() => {
      timer = null;
      fn(...args);
    }, delayMs);
  });
}
function clampNumber(value, fallback, min, max) {
  const parsed = typeof value === "number" ? value : Number.parseInt(String(value != null ? value : ""), 10);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(max, Math.max(min, Math.round(parsed)));
}
function clampOpacity(value, fallback) {
  const parsed = typeof value === "number" ? value : Number.parseFloat(String(value != null ? value : ""));
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(1, Math.max(0.2, parsed));
}
function createPopoutWindowInit(sticky, hideWindowTitlebar) {
  const init = {
    x: sticky.x,
    y: sticky.y,
    size: {
      width: sticky.width,
      height: sticky.height
    }
  };
  if (hideWindowTitlebar) {
    Object.assign(init, {
      frame: false,
      titleBarStyle: "hidden",
      titleBarOverlay: false,
      autoHideMenuBar: true,
      backgroundColor: "#00000000"
    });
  }
  return init;
}
var DesktopStickyNotesPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = cloneDefaultSettings();
    this.openLeavesBySticky = /* @__PURE__ */ new Map();
    this.cleanupByLeaf = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_STICKY_NOTE, (leaf) => new StickyNoteView(leaf, this));
    this.addSettingTab(new DesktopStickyNotesSettingTab(this.app, this));
    this.addRibbonIcon("sticky-note", "\u5C06\u5F53\u524D\u7B14\u8BB0\u8D34\u5230\u684C\u9762", () => {
      void this.pinCurrentNote();
    });
    this.addCommand({
      id: "pin-current-note-as-desktop-sticky",
      name: "\u5C06\u5F53\u524D\u7B14\u8BB0\u8D34\u5230\u684C\u9762",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        const canRun = Boolean(file && file.extension === "md");
        if (!canRun) return false;
        if (!checking && file) void this.pinFile(file);
        return true;
      }
    });
    this.addCommand({
      id: "pin-note-as-desktop-sticky",
      name: "\u9009\u62E9\u7B14\u8BB0\u5E76\u8D34\u5230\u684C\u9762",
      callback: () => {
        new NoteSuggestModal(this.app, (file) => {
          void this.pinFile(file);
        }).open();
      }
    });
    this.addCommand({
      id: "create-new-desktop-sticky-note",
      name: "\u65B0\u5EFA\u684C\u9762\u4FBF\u7B7E",
      callback: () => {
        void this.createNewStickyNote();
      }
    });
    this.addCommand({
      id: "restore-desktop-sticky-notes",
      name: "\u6062\u590D\u6240\u6709\u684C\u9762\u4FBF\u7B7E",
      callback: () => {
        void this.restoreStickies();
      }
    });
    this.addCommand({
      id: "close-all-desktop-sticky-notes",
      name: "\u5173\u95ED\u6240\u6709\u684C\u9762\u4FBF\u7B7E\u7A97\u53E3",
      callback: () => {
        void this.closeAllStickyWindows();
      }
    });
    this.addCommand({
      id: "toggle-always-on-top-for-open-sticky-notes",
      name: "\u5207\u6362\u6240\u6709\u5DF2\u6253\u5F00\u4FBF\u7B7E\u7684\u7F6E\u9876\u72B6\u6001",
      callback: () => {
        void this.toggleAlwaysOnTopForOpenStickies();
      }
    });
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      if (!(file instanceof import_obsidian5.TFile) || file.extension !== "md") return;
      menu.addItem((item) => item.setTitle("\u8D34\u5230\u684C\u9762\u4FBF\u7B7E").setIcon("sticky-note").onClick(() => {
        void this.pinFile(file);
      }));
    }));
    this.registerEvent(this.app.vault.on("delete", async (file) => {
      if (!(file instanceof import_obsidian5.TFile)) return;
      const matchingIds = Object.values(this.settings.stickies).filter((sticky) => sticky.filePath === file.path).map((sticky) => sticky.id);
      for (const id of matchingIds) await this.removeSticky(id, true);
    }));
    this.registerEvent(this.app.vault.on("rename", async (file, oldPath) => {
      if (!(file instanceof import_obsidian5.TFile)) return;
      let changed = false;
      for (const sticky of Object.values(this.settings.stickies)) {
        if (sticky.filePath === oldPath) {
          sticky.filePath = file.path;
          sticky.updatedAt = Date.now();
          changed = true;
        }
      }
      if (changed) await this.saveSettings();
    }));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.restoreOnStartup) void this.restoreStickies();
    });
  }
  async onunload() {
    await this.closeAllStickyWindows();
    for (const cleanup of this.cleanupByLeaf.values()) cleanup();
    this.cleanupByLeaf.clear();
  }
  async loadSettings() {
    var _a;
    const loaded = await this.loadData();
    this.settings = {
      ...cloneDefaultSettings(),
      ...loaded,
      stickies: (_a = loaded == null ? void 0 : loaded.stickies) != null ? _a : {}
    };
    this.settings.defaultWidth = clampNumber(this.settings.defaultWidth, DEFAULT_SETTINGS.defaultWidth, 240, 1600);
    this.settings.defaultHeight = clampNumber(this.settings.defaultHeight, DEFAULT_SETTINGS.defaultHeight, 180, 1600);
    this.settings.defaultOpacity = clampOpacity(this.settings.defaultOpacity, DEFAULT_SETTINGS.defaultOpacity);
    this.settings.autoSaveDelayMs = clampNumber(this.settings.autoSaveDelayMs, DEFAULT_SETTINGS.autoSaveDelayMs, 200, 1e4);
    for (const sticky of Object.values(this.settings.stickies)) {
      sticky.width = clampNumber(sticky.width, this.settings.defaultWidth, 240, 1600);
      sticky.height = clampNumber(sticky.height, this.settings.defaultHeight, 180, 1600);
      sticky.opacity = clampOpacity(sticky.opacity, this.settings.defaultOpacity);
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    return file instanceof import_obsidian5.TFile && file.extension === "md" ? file : null;
  }
  async pinCurrentNote() {
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      new import_obsidian5.Notice("\u5F53\u524D\u6CA1\u6709\u53EF\u8D34\u5230\u684C\u9762\u7684 Markdown \u7B14\u8BB0\u3002", 4e3);
      return;
    }
    await this.pinFile(file);
  }
  async pinFile(file) {
    if (!import_obsidian5.Platform.isDesktopApp) {
      new import_obsidian5.Notice("Desktop Sticky Notes \u53EA\u80FD\u5728 Obsidian \u684C\u9762\u7AEF\u4F7F\u7528\u3002", 5e3);
      return;
    }
    if (this.settings.reuseExistingStickyForSameFile) {
      const existing = Object.values(this.settings.stickies).find((sticky2) => sticky2.filePath === file.path);
      if (existing) {
        await this.openSticky(existing.id);
        return;
      }
    }
    const sticky = this.createStickyState(file.path);
    this.settings.stickies[sticky.id] = sticky;
    await this.saveSettings();
    await this.openSticky(sticky.id);
  }
  async openSticky(stickyId) {
    const sticky = this.settings.stickies[stickyId];
    if (!sticky) {
      new import_obsidian5.Notice("\u627E\u4E0D\u5230\u8FD9\u4E2A\u4FBF\u7B7E\u7684\u72B6\u6001\u3002", 4e3);
      return;
    }
    const file = this.getFile(sticky.filePath);
    if (!file) {
      new import_obsidian5.Notice(`\u627E\u4E0D\u5230\u7B14\u8BB0\uFF1A${sticky.filePath}`, 6e3);
      return;
    }
    const existingLeaf = this.firstOpenLeaf(stickyId);
    if (existingLeaf) {
      this.focusLeaf(existingLeaf);
      return;
    }
    try {
      const leaf = this.app.workspace.openPopoutLeaf(
        createPopoutWindowInit(sticky, this.settings.hideWindowTitlebar)
      );
      applyWindowBounds(leaf, sticky);
      await leaf.setViewState({
        type: VIEW_TYPE_STICKY_NOTE,
        state: { stickyId },
        active: true
      });
      this.markStickyOpened(stickyId, leaf);
      await this.touchSticky(stickyId, { lastOpenedAt: Date.now() });
      const currentSticky = this.settings.stickies[stickyId];
      applyWindowPreferences(leaf, currentSticky, {
        skipTaskbar: this.settings.skipTaskbar,
        hideWindowTitlebar: this.settings.hideWindowTitlebar,
        showNotice: true
      });
      applyWindowBounds(leaf, currentSticky);
      this.setupWindowPersistence(stickyId, leaf);
      this.scheduleInitialWindowSync(stickyId, leaf);
      if (this.settings.focusNewSticky) this.focusLeaf(leaf);
    } catch (error) {
      console.error("Desktop Sticky Notes: failed to open sticky window", error);
      new import_obsidian5.Notice("\u65E0\u6CD5\u6253\u5F00\u684C\u9762\u4FBF\u7B7E\u7A97\u53E3\u3002\u8BF7\u786E\u8BA4\u5F53\u524D\u662F Obsidian \u684C\u9762\u7AEF\u3002", 6e3);
    }
  }
  async restoreStickies() {
    const stickies = Object.values(this.settings.stickies).sort((a, b) => {
      var _a, _b;
      return ((_a = a.lastOpenedAt) != null ? _a : a.createdAt) - ((_b = b.lastOpenedAt) != null ? _b : b.createdAt);
    });
    for (const sticky of stickies) {
      if (this.getFile(sticky.filePath)) await this.openSticky(sticky.id);
    }
  }
  async closeAllStickyWindows() {
    const leaves = /* @__PURE__ */ new Set();
    for (const leafSet of this.openLeavesBySticky.values()) {
      for (const leaf of leafSet) leaves.add(leaf);
    }
    for (const leaf of leaves) {
      try {
        leaf.detach();
      } catch (_error) {
      }
      this.cleanupLeaf(leaf);
    }
    this.openLeavesBySticky.clear();
  }
  async toggleAlwaysOnTopForOpenStickies() {
    const openStickyIds = [...this.openLeavesBySticky.keys()];
    if (openStickyIds.length === 0) {
      new import_obsidian5.Notice("\u5F53\u524D\u6CA1\u6709\u6253\u5F00\u7684\u684C\u9762\u4FBF\u7B7E\u3002", 3e3);
      return;
    }
    const shouldEnable = openStickyIds.some((id) => {
      var _a;
      return !((_a = this.settings.stickies[id]) == null ? void 0 : _a.alwaysOnTop);
    });
    for (const id of openStickyIds) {
      const sticky = this.settings.stickies[id];
      if (!sticky) continue;
      sticky.alwaysOnTop = shouldEnable;
      sticky.updatedAt = Date.now();
    }
    await this.saveSettings();
    await this.applyPreferencesToOpenStickies();
    new import_obsidian5.Notice(shouldEnable ? "\u5DF2\u5C06\u6240\u6709\u4FBF\u7B7E\u8BBE\u4E3A\u7F6E\u9876\u3002" : "\u5DF2\u53D6\u6D88\u6240\u6709\u4FBF\u7B7E\u7F6E\u9876\u3002", 3e3);
  }
  async applyPreferencesToOpenStickies() {
    for (const [stickyId, leaves] of this.openLeavesBySticky.entries()) {
      const sticky = this.settings.stickies[stickyId];
      if (!sticky) continue;
      for (const leaf of leaves) {
        applyWindowPreferences(leaf, sticky, {
          skipTaskbar: this.settings.skipTaskbar,
          hideWindowTitlebar: this.settings.hideWindowTitlebar,
          showNotice: false
        });
      }
    }
  }
  async applyDefaultSizeToAllStickies() {
    const width = this.settings.defaultWidth;
    const height = this.settings.defaultHeight;
    let changed = 0;
    for (const sticky of Object.values(this.settings.stickies)) {
      if (sticky.width === width && sticky.height === height) continue;
      sticky.width = width;
      sticky.height = height;
      sticky.updatedAt = Date.now();
      changed += 1;
    }
    await this.saveSettings();
    for (const [stickyId, leaves] of this.openLeavesBySticky.entries()) {
      const sticky = this.settings.stickies[stickyId];
      if (!sticky) continue;
      for (const leaf of leaves) applyWindowBounds(leaf, sticky);
    }
    new import_obsidian5.Notice(changed > 0 ? `\u5DF2\u5C06 ${changed} \u4E2A\u4FBF\u7B7E\u8C03\u6574\u4E3A\u5F53\u524D\u9ED8\u8BA4\u5C3A\u5BF8\u3002` : "\u6240\u6709\u4FBF\u7B7E\u5DF2\u7ECF\u662F\u5F53\u524D\u9ED8\u8BA4\u5C3A\u5BF8\u3002", 3e3);
  }
  async updateSticky(stickyId, patch, persist = true) {
    const sticky = this.settings.stickies[stickyId];
    if (!sticky) return;
    this.settings.stickies[stickyId] = {
      ...sticky,
      ...patch,
      updatedAt: Date.now()
    };
    if (persist) await this.saveSettings();
  }
  async touchSticky(stickyId, patch = {}) {
    await this.updateSticky(stickyId, patch, true);
  }
  async removeSticky(stickyId, closeOpenWindows) {
    var _a;
    if (closeOpenWindows) {
      const leaves = [...(_a = this.openLeavesBySticky.get(stickyId)) != null ? _a : []];
      for (const leaf of leaves) {
        try {
          leaf.detach();
        } catch (_error) {
        }
        this.cleanupLeaf(leaf);
      }
    }
    this.openLeavesBySticky.delete(stickyId);
    delete this.settings.stickies[stickyId];
    await this.saveSettings();
  }
  markStickyClosed(stickyId, leaf) {
    const leaves = this.openLeavesBySticky.get(stickyId);
    if (leaves) {
      leaves.delete(leaf);
      if (leaves.size === 0) this.openLeavesBySticky.delete(stickyId);
    }
    this.cleanupLeaf(leaf);
  }
  async createNewStickyNote() {
    if (!import_obsidian5.Platform.isDesktopApp) {
      new import_obsidian5.Notice("Desktop Sticky Notes \u53EA\u80FD\u5728 Obsidian \u684C\u9762\u7AEF\u4F7F\u7528\u3002", 5e3);
      return;
    }
    try {
      const folderPath = (0, import_obsidian5.normalizePath)(this.settings.newNoteFolder.trim());
      await this.ensureFolder(folderPath);
      const now = (0, import_obsidian5.moment)();
      const baseName = `Sticky ${now.format("YYYY-MM-DD HHmmss")}`;
      const path = this.getAvailableMarkdownPath(folderPath, baseName);
      const template = this.settings.newNoteTemplate.replace(/{{date}}/g, now.format("YYYY-MM-DD")).replace(/{{time}}/g, now.format("HH:mm"));
      const content = template.length > 0 ? template : `# ${now.format("YYYY-MM-DD HH:mm")}

`;
      const file = await this.app.vault.create(path, content);
      await this.pinFile(file);
    } catch (error) {
      console.error("Desktop Sticky Notes: failed to create note", error);
      new import_obsidian5.Notice("\u65B0\u5EFA\u684C\u9762\u4FBF\u7B7E\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u76EE\u5F55\u8BBE\u7F6E\u3002", 6e3);
    }
  }
  createStickyState(filePath) {
    var _a, _b;
    const count = Object.keys(this.settings.stickies).length;
    const offset = count % 8 * 28;
    const screenInfo = window.screen;
    const screenLeft = Math.max(40, ((_a = screenInfo.availLeft) != null ? _a : 0) + 80 + offset);
    const screenTop = Math.max(40, ((_b = screenInfo.availTop) != null ? _b : 0) + 80 + offset);
    const now = Date.now();
    return {
      id: makeId(),
      filePath,
      x: screenLeft,
      y: screenTop,
      width: this.settings.defaultWidth,
      height: this.settings.defaultHeight,
      mode: this.settings.defaultMode,
      color: this.settings.defaultColor,
      alwaysOnTop: this.settings.defaultAlwaysOnTop,
      opacity: this.settings.defaultOpacity,
      createdAt: now,
      updatedAt: now,
      lastOpenedAt: now
    };
  }
  firstOpenLeaf(stickyId) {
    const leaves = this.openLeavesBySticky.get(stickyId);
    if (!leaves) return null;
    for (const leaf of leaves) return leaf;
    return null;
  }
  focusLeaf(leaf) {
    var _a, _b;
    try {
      (_b = (_a = getBrowserWindowForLeaf(leaf)) == null ? void 0 : _a.focus) == null ? void 0 : _b.call(_a);
    } catch (_error) {
    }
    try {
      this.app.workspace.setActiveLeaf(leaf, { focus: true });
    } catch (_error) {
    }
  }
  markStickyOpened(stickyId, leaf) {
    var _a;
    const leaves = (_a = this.openLeavesBySticky.get(stickyId)) != null ? _a : /* @__PURE__ */ new Set();
    leaves.add(leaf);
    this.openLeavesBySticky.set(stickyId, leaves);
  }
  scheduleInitialWindowSync(stickyId, leaf) {
    for (const delayMs of [50, 150, 350, 750, 1500, 3e3]) {
      const timer = window.setTimeout(() => {
        var _a;
        if (!((_a = this.openLeavesBySticky.get(stickyId)) == null ? void 0 : _a.has(leaf))) return;
        const sticky = this.settings.stickies[stickyId];
        if (!sticky) return;
        applyWindowPreferences(leaf, sticky, {
          skipTaskbar: this.settings.skipTaskbar,
          hideWindowTitlebar: this.settings.hideWindowTitlebar,
          showNotice: false
        });
        applyWindowBounds(leaf, sticky);
      }, delayMs);
      this.register(() => window.clearTimeout(timer));
    }
  }
  setupWindowPersistence(stickyId, leaf) {
    var _a, _b, _c;
    const browserWindow = getBrowserWindowForLeaf(leaf);
    if (!browserWindow) return;
    const persistBounds = debounce(() => {
      var _a2;
      if ((_a2 = browserWindow.isDestroyed) == null ? void 0 : _a2.call(browserWindow)) return;
      const patch = captureWindowBounds(browserWindow);
      if (!patch) return;
      void this.updateSticky(stickyId, patch, true);
    }, 300);
    const cleanup = () => {
      var _a2, _b2, _c2;
      try {
        (_a2 = browserWindow.removeListener) == null ? void 0 : _a2.call(browserWindow, "move", persistBounds);
        (_b2 = browserWindow.removeListener) == null ? void 0 : _b2.call(browserWindow, "resize", persistBounds);
        (_c2 = browserWindow.removeListener) == null ? void 0 : _c2.call(browserWindow, "closed", cleanup);
      } catch (_error) {
      }
      this.cleanupByLeaf.delete(leaf);
    };
    try {
      (_a = browserWindow.on) == null ? void 0 : _a.call(browserWindow, "move", persistBounds);
      (_b = browserWindow.on) == null ? void 0 : _b.call(browserWindow, "resize", persistBounds);
      (_c = browserWindow.on) == null ? void 0 : _c.call(browserWindow, "closed", cleanup);
      this.cleanupByLeaf.set(leaf, cleanup);
    } catch (_error) {
    }
  }
  cleanupLeaf(leaf) {
    const cleanup = this.cleanupByLeaf.get(leaf);
    if (cleanup) cleanup();
  }
  async ensureFolder(folderPath) {
    const normalized = (0, import_obsidian5.normalizePath)(folderPath).replace(/^\/+|\/+$/g, "");
    if (!normalized) return;
    const parts = normalized.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing instanceof import_obsidian5.TFolder) continue;
      if (existing) throw new Error(`Path exists but is not a folder: ${current}`);
      await this.app.vault.createFolder(current);
    }
  }
  getAvailableMarkdownPath(folderPath, baseName) {
    const folder = (0, import_obsidian5.normalizePath)(folderPath).replace(/^\/+|\/+$/g, "");
    const prefix = folder ? `${folder}/` : "";
    let candidate = (0, import_obsidian5.normalizePath)(`${prefix}${baseName}.md`);
    let index = 2;
    while (this.app.vault.getAbstractFileByPath(candidate)) {
      candidate = (0, import_obsidian5.normalizePath)(`${prefix}${baseName} ${index}.md`);
      index += 1;
    }
    return candidate;
  }
};
